baseURL = "http://example.com/"
languageCode = "en-gb"
title = "Shoelace"
theme = "shoelace"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
enableRobotsTXT = true

[params]
    author = "Gareth J Barnard"
    description = "Personal blog theme powered by Hugo"
    githubUsername = "#"
    accent = "#fc0"
    showBorder = true
    backgroundColor = "#eee"
    font = "Open Sans" # Should match the name in the assets/scss/_fonts file.

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    style = 'dracula'
    tabWidth = 4

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

[[menu.main]]
    url = "/theme/"
    name = "Theme"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/username/"
    name = "fab fa-linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/username/"
    name = "fab fa-stack-overflow"
    weight = 5
