baseURL = ""
languageCode = "en-gb"
title = "Shoelace"
theme = "shoelace"
disqusShortname = "" # delete this to disable disqus comments otherwise 'username'
googleAnalytics = ""
enableRobotsTXT = true

[params]
    author = "Gareth J Barnard"
    description = "Personal blog theme evolved from Minimal and powered by Hugo"
    githubUsername = "#"
    accent = "#fc0"
    showBorder = true
    backgroundColour = "#fcfcfc"
    hasBackgroundColour = "#fcfcfce6"
    font = "Open Sans" # Should match the name in the assets/scss/fonts file.
    fullbs = false # Set to true to use the full version of Bootstrap with both the CSS and JS.

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    style = 'dracula'
    tabWidth = 4

menu = ['main', 'icon']

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1
    [menu.main.params]
        icon = "fa-solid fa-house"

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2
    [menu.main.params]
        icon = "fa-solid fa-circle-info"

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3
    [menu.main.params]
        icon = "fa-solid fa-newspaper"

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4
    [menu.main.params]
        icon = "fa-solid fa-diagram-project"

[[menu.main]]
    url = "/theme/"
    name = "Theme"
    weight = 5
    [menu.main.params]
        icon = "fa-solid fa-brush"

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "Mail"
    weight = 1
    [menu.icon.params]
        icon = "fa-solid fa-envelope"

[[menu.icon]]
    url = "https://github.com/username/"
    name = "Github"
    weight = 2
    [menu.icon.params]
        icon = "fa-brands fa-github"

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "Twitter"
    weight = 3
    [menu.icon.params]
        icon = "fa-brands fa-twitter"

[[menu.icon]]
    url = "https://www.linkedin.com/in/username/"
    name = "Linkedin"
    weight = 4
    [menu.icon.params]
        icon = "fa-brands fa-linkedin"

[[menu.icon]]
    url = "https://www.stackoverflow.com/username/"
    name = "Stackoverflow"
    weight = 5
    [menu.icon.params]
        icon = "fa-brands fa-stack-overflow"
